import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "@/store/store.provider";
import { getAuthApi } from "@/apis/authApi";
import { getCurrentUser } from "@/apis/server-side/getCurrentUser";




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,  
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider currentUser={currentUser}>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
