import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { StoreProvider } from "@/store/store.provider";
import { getCurrentUser } from "@/apis/server-side/getCurrentUser";
import { redirect } from "next/navigation";
import { isStillLoggedIn } from "@/apis/server-side/isStillLoggedIn";




const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,  
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isLoggedIn = await isStillLoggedIn();
  if(!isLoggedIn){
    redirect('/login');
  }

  const currentUser = await getCurrentUser();  


  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>
      <body className={inter.className}>
        <StoreProvider currentUser={currentUser}>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
